########## Testcase 0: Failed ##########
Expected Output: 
76.8
6

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
5.5
1

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
1
6

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
5
4

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
0
8

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
5654134.9
10

Your Output: 
Traceback (most recent call last):
  File "Deep_List.py", line 1, in <module>
    from pythonds.basic.stack import Stack
ModuleNotFoundError: No module named 'pythonds'
----------------------------------------

