########## Testcase 0: Failed ##########
Expected Output: 
Alice

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 29, in <module>
    main()
  File "Dice.py", line 25, in main
    ans = list(val)
TypeError: 'int' object is not iterable
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
Mark

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 29, in <module>
    main()
  File "Dice.py", line 25, in main
    ans = list(val)
TypeError: 'int' object is not iterable
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
Bob

Your Output: 
Traceback (most recent call last):
  File "Dice.py", line 29, in <module>
    main()
  File "Dice.py", line 25, in main
    ans = list(val)
TypeError: 'int' object is not iterable
----------------------------------------

